import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import ReduxProvider from "@/provider";
import { ToastContainer } from "react-toastify";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen o`}>
        <ReduxProvider>
          <Header />
          <ToastContainer />
          <main className="flex-grow">
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
